megam_chef:
      config: 'development'      
development: 
      source: 'riak'
      host: 'localhost'
      port: '8098'
      bucket: '-prov'
production: 
      source: 'riak'
      host: 'riak.megam.co'
      port: 8098
      bucket: 'megam_prov'

